<?xml version="1.0" encoding="utf-8"?><Database Name="QLSach" Class="DBSachDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-H51AT8T\SQLEXPRESS;Initial Catalog=QLSach;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QLSachConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Sach" Member="Saches">
    <Type Name="Sach">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Conten" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="AuthorName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>